### ISSUE TITLE
No keyboard & cant receive SMS anymore

### ISSUE THREAD

**Issue by matt32106** [0x192/Universal-Android-Debloater#120]
I uninstalled most of the recommended features on my phone (Realme GT). 

1/ I had no keyboard after removing the recommended bits (see list in below message). I installed MS keyboard (that did not need me typing anything fortunately).

2/ I installed an SMS app from Fdroid (simplemobiletools) but I can't receive SMS anymore (sending is ok). How do I reactivate what is needed?

<details>
<summary>Uninstalled blobs</summary>

```
com.android.bips
com.android.bluetoothmidiservice
com.android.bookmarkprovider
com.android.carrierdefaultapp
com.android.chrome
com.android.companiondevicemanager
com.android.email.partnerprovider
com.android.hotwordenrollment.okgoogle
com.android.htmlviewer
com.android.providers.calendar
com.android.providers.partnerbookmarks
com.android.stk
com.android.traceur
com.android.wallpaper.livepicker
com.coloros.childrenspace
com.coloros.gamespace
com.coloros.healthcheck
com.coloros.oppomultiapp
com.coloros.soundrecorder
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.google.android.apps.googleassistant
com.google.android.apps.messaging
com.google.android.apps.photos
com.google.android.apps.restore
com.google.android.apps.setupwizard.searchselector
com.google.android.apps.walletnfcrel
com.google.android.apps.wellbeing
com.google.android.apps.work.oobconfig
com.google.android.calendar
com.google.android.configupdater
com.google.android.contacts
com.google.android.feedback
com.google.android.gms.location.history
com.google.android.googlequicksearchbox
com.google.android.inputmethod.latin
com.google.android.keep
com.google.android.marvin.talkback
com.google.android.onetimeinitializer
com.google.android.partnersetup
com.google.android.printservice.recommendation
com.google.android.projection.gearhead
com.google.android.setupwizard
com.google.android.syncadapters.contacts
com.google.android.tag
com.google.android.tts
com.google.android.youtube
com.google.ar.core
com.google.ar.lens
com.netflix.partner.activation
com.oppo.quicksearchbox
com.qti.confuridialer
com.qti.qualcomm.datastatusnotification
com.qti.service.colorservice
com.qti.snapdragon.qdcm_ff
com.qti.xdivert
com.qualcomm.atfwd
com.qualcomm.qti.callfeaturessetting
com.tencent.soter.soterserver
com.wapi.wapicertmanage
```
</details>

**Comment by matt32106** [comment]
Uninstalled blobs:
```
com.android.bips
com.android.bluetoothmidiservice
com.android.bookmarkprovider
com.android.carrierdefaultapp
com.android.chrome
com.android.companiondevicemanager
com.android.email.partnerprovider
com.android.hotwordenrollment.okgoogle
com.android.htmlviewer
com.android.providers.calendar
com.android.providers.partnerbookmarks
com.android.stk
com.android.traceur
com.android.wallpaper.livepicker
com.coloros.childrenspace
com.coloros.gamespace
com.coloros.healthcheck
com.coloros.oppomultiapp
com.coloros.soundrecorder
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.google.android.apps.googleassistant
com.google.android.apps.messaging
com.google.android.apps.photos
com.google.android.apps.restore
com.google.android.apps.setupwizard.searchselector
com.google.android.apps.walletnfcrel
com.google.android.apps.wellbeing
com.google.android.apps.work.oobconfig
com.google.android.calendar
com.google.android.configupdater
com.google.android.contacts
com.google.android.feedback
com.google.android.gms.location.history
com.google.android.googlequicksearchbox
com.google.android.inputmethod.latin
com.google.android.keep
com.google.android.marvin.talkback
com.google.android.onetimeinitializer
com.google.android.partnersetup
com.google.android.printservice.recommendation
com.google.android.projection.gearhead
com.google.android.setupwizard
com.google.android.syncadapters.contacts
com.google.android.tag
com.google.android.tts
com.google.android.youtube
com.google.ar.core
com.google.ar.lens
com.netflix.partner.activation
com.oppo.quicksearchbox
com.qti.confuridialer
com.qti.qualcomm.datastatusnotification
com.qti.service.colorservice
com.qti.snapdragon.qdcm_ff
com.qti.xdivert
com.qualcomm.atfwd
com.qualcomm.qti.callfeaturessetting
com.tencent.soter.soterserver
com.wapi.wapicertmanage
```

**Comment by 0x192** [comment]
Please follow the issue template (` Debloat issue report `). Don't open a blank issue like this. 

You didn't tell me the UAD version you used and I prefer having the full logfile.

Concerning your problem:

1) Thanks for letting me know. Default keyboard should not be in the `Recommended` list. I will move Google Keyboard (`com.google.android.inputmethod.latin`) into the `Advanced` list.

2) I don't understand how you could send but not receive SMS. Are you sure it's not the MMS you can't receive? Honestly, from the packages list you gave me I don't know which one could be the culprit (hopefully there is only one)

So you can try by dichotomy:
1) Restore all the packages and check your issue is fixed
2) Uninstall the first half of the `Recommended` list. 
3) Check if you have the issue
4) If you have the issue, you know the culprit is in this half. Restore the packages and uninstall the half of this set. Go back to 3
If you don't have the issue, you know the culprit is in the other half. You know what to do...

**Comment by matt32106** [comment]
Oops sorry for the issue template, missed that. Version used is 0.4.1.

**Comment by lawson85** [comment]
com.google.android.inputmethod.latin is your keyboard. 

com.google.android.apps.messaging is your SMS app. I'm wondering if receiving issues are to do with RCS

**Comment by 9034725985** [comment]
One workaround is to somehow (I used email) to send a link to the gboard and go to that link and install Google Keyboard.

https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin&hl=en_US&gl=US

I agree with the original poster. Google Keyboard should not be on the recommended list at least for devices that do not have an alternate input method specified.

**Comment by matt32106** [comment]
> com.google.android.apps.messaging is your SMS app. I'm wondering if receiving issues are to do with RCS

Re-enabling com.google.android.apps.messaging only does not solve the issue. I still can't receive SMS and sending still ok. I will try the dichotomy thing when I have enough time in front of me.
(note : I did not restart the phone after re-enabling it)

**Comment by matt32106** [comment]
I just re-enabled everything and restarted the phone. Still not receiving SMS... :( Something wrong here not necessarily linked to uad then.

**Comment by lawson85** [comment]
If you remove your sim and reboot then add your sim and reboot, it may work again

**Comment by 0x192** [comment]
@matt32106 
Keep us informed. I hope you will be able to fix this quite serious problem.

**Comment by matt32106** [comment]
@0x192 Well, this is not at all related to UAD AFAICT. Some phones cannot msg me, especially my work phone (W) cannot message my personal phone (P) but I received MFA SMS on it without problem. I thought maybe I had blocked my workphone as a spammer but that is not the case. W -> P does not work. P -> W works. I need to do more testing. I did not try to remove the SIM and reboot yet.

**Comment by Jipok** [comment]
Realme GT NEO 3 with Chinese ROM cant receive sms/mms on qksms or Simple SMS Messenger. Only default com.android.mms works.
